server:
  port: 9527

spring:
  application:
    name: microservicecloud-zull-gateway

eureka:
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7000.com:7000/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    instance:
      instance-id: gateway-9527.com
      prefer-ip: true
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.patch: /mydept/**
  prefix: /runningsss
  ignored-services: "*"
info:
  app.name: runningsss-microcloud
  company.name: www.runningsss.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$






